In [1]:
import pandas as pd

In [2]:
us_women_medals = pd.read_csv('women_medal.csv')
us_men_medals = pd.read_csv('men_medal.csv')

In [3]:
# Convert total medal counts to medals per simulation
us_women_medals[us_women_medals.columns[2:]] = us_women_medals[us_women_medals.columns[2:]]/10000
us_men_medals[us_men_medals.columns[2:]] = us_men_medals[us_men_medals.columns[2:]]/10000

In [4]:
# Find the top lineup for any given value for each type of medal
def best_team(df, values_list):
    df['Count'] = (
        values_list[0]*df['Apparatus gold'] + 
        values_list[1]*df['Apparatus silver'] + 
        values_list[2]*df['Apparatus bronze'] + 
        values_list[3]*df['Indv. AA gold'] + 
        values_list[4]*df['Indv. AA silver'] + 
        values_list[5]*df['Indv. AA bronze'] + 
        values_list[6]*df['Team AA gold'] +
        values_list[7]*df['Team AA silver'] + 
        values_list[8]*df['Team AA bronze'] 
    )
    return df.loc[df['Count'].idxmax(), 'gymnasts'].replace("'", '').replace("(", '').replace(")", '').split(", ")

In [5]:
# simplify putting in weights
def score_list(medals, event_type):
    gold, silver, bronze = medals
    Team, i_AA, app = event_type
    scoring_parameters = []
    for i in range(9):
        score = 1
        if i % 3 == 0:
            score *= gold
        elif i % 3 == 1:
            score *= silver
        else:
            score *= bronze
        if i < 3:
            score *= app
        elif i < 6:
            score *= i_AA
        else:
            score *= Team
        scoring_parameters.append(score)
    return scoring_parameters

In [6]:
# Find best lineup for 5 different weighting measures
lineup_suggestions = {'men': {}, 'women': {}}
for gender in lineup_suggestions.keys():
    if gender == 'men':
        df = us_men_medals
    else:
        df = us_women_medals
    lineup_suggestions[gender]['Total Medals'] = best_team(df, score_list((1,1,1), (1,1,1)))
    lineup_suggestions[gender]['Weighted by Type of Medal'] = best_team(df, score_list((3,2,1), (1,1,1)))
    lineup_suggestions[gender]['Higher Weight for Team Medal'] = best_team(df, score_list((1,1,1), (5,1,1)))
    lineup_suggestions[gender]['Higher Weight for Team & Indv. AA Medal'] = best_team(df, score_list((1,1,1), (5,3,1)))
    lineup_suggestions[gender]['Higher Weight for Type of Medal, Team & Indv. AA Medal'] = best_team(df, score_list((3,2,1), (5,3,1)))

In [7]:
pd.DataFrame(lineup_suggestions['men']).T.rename_axis("Male Competition Recommendation")

,0,1,2,3,4
Male Competition Recommendation,,,,,
Total Medals,Vitaliy GUIMARAES,Brody MALONE,Paul JUDA,Khoi YOUNG,Donnell WHITTENBURG
Weighted by Type of Medal,Vitaliy GUIMARAES,Brody MALONE,Asher HONG,Khoi YOUNG,Donnell WHITTENBURG
Higher Weight for Team Medal,Vitaliy GUIMARAES,Brody MALONE,Paul JUDA,Khoi YOUNG,Donnell WHITTENBURG
Higher Weight for Team & Indv. AA Medal,Vitaliy GUIMARAES,Brody MALONE,Paul JUDA,Khoi YOUNG,Alex DIAB
"Higher Weight for Type of Medal, Team & Indv. AA Medal",Vitaliy GUIMARAES,Brody MALONE,Paul JUDA,Khoi YOUNG,Donnell WHITTENBURG

In [8]:
pd.DataFrame(lineup_suggestions['women']).T.rename_axis("Female Competition Recommendation")

,0,1,2,3,4
Female Competition Recommendation,,,,,
Total Medals,Simone BILES,Shilese JONES,Sunisa LEE,Jade CAREY,Konnor MCCLAIN
Weighted by Type of Medal,Simone BILES,Shilese JONES,Sunisa LEE,Jade CAREY,Konnor MCCLAIN
Higher Weight for Team Medal,Simone BILES,Shilese JONES,Sunisa LEE,Jade CAREY,Konnor MCCLAIN
Higher Weight for Team & Indv. AA Medal,Simone BILES,Shilese JONES,Sunisa LEE,Jade CAREY,Konnor MCCLAIN
"Higher Weight for Type of Medal, Team & Indv. AA Medal",Simone BILES,Shilese JONES,Sunisa LEE,Jade CAREY,Konnor MCCLAIN